### ISSUE TITLE
connect.static (not .staticProvider) in /examples/debug/server.js

### ISSUE THREAD

**Issue by bensheldon** [aaronblohowiak/Push-It#13]
Line 22-24 of [/examples/debug/server.js](https://github.com/aaronblohowiak/Push-It/blob/master/examples/debug/server.js) is:

``` javascript
var server = connect.createServer( 
  connect.staticProvider(__dirname + '/static')
);
```

...but should be...

``` javascript
var server = connect.createServer( 
  connect.static(__dirname + '/static')
);
```

Sorry for the minor bugfix, but it throws an error and seems like a [common-ish issue](http://stackoverflow.com/questions/7135143/connect-staticprovider-problem).

**Comment by aaronblohowiak** [comment]
this was only in the `examples/debug/server.js`, so I added the connect 0.1.0 devDependency which will pull in the version of connect that used staticProvider instead of static.
