### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by vizo** [aaronblohowiak/Push-It#18]

**Comment by Rajan** [comment]
It doesn't look like that. I recommend using node.js instead.

**Comment by vizo** [comment]
node.js? I use node.js but i need transport layer (websockets with fallback) and some wrapper like push-it :)

**Comment by aaronblohowiak** [comment]
No, sorry.  This repo is no longer maintained.  Please use SockJS or Socket.io directly.

**Comment by vizo** [comment]
Ok thanks for answering me :)
