### ISSUE TITLE
Client can crash the server

### ISSUE THREAD

**Issue by robbi5** [aaronblohowiak/Push-It#2]
The client can simply crash the server when it sends a message to the /meta/onMessage channel.
`pushIt.sendMessage({"channel": "/meta/onMessage"});`

Bug is in push-it-proto.js, line 50 (https://github.com/aaronblohowiak/Push-It/blob/827c704/server/etc/push-it-proto.js#L50). There should be a check for allowed methods like connect and subscribe.

**Comment by aaronblohowiak** [comment]
Good catch, I will add a test and a fix later tonight.

**Comment by aaronblohowiak** [comment]
https://github.com/aaronblohowiak/Push-It/commit/cff45b2a48a106a439fb0647d4a0114e716b8e0f Adds test & fix.

**Comment by robbi5** [comment]
Sorry, but this doesn't fix the Crash. Clients can still call `pushIt.sendMessage({"channel": "/meta/onMessage"});` and the server crashes, because it is stuck in an endless loop of calling onMessage (which calls onMessage on line 52). I think you should use a blacklist for channel-names here. I can provide a testpage for this, if you want.

**Comment by aaronblohowiak** [comment]
https://github.com/aaronblohowiak/Push-It/commit/a98b1239553a878276c208d1f4f0a3f3128a09d0

Okay, I whitelisted connect and subscribe as they are the only /meta/ operations going on and the dynamic dispatch code was more confusing.  The latest commit should have fixed all of these issues.

Thanks for the feedback.
- Aaron

**Comment by robbi5** [comment]
Great, thanks for your fast bugfix :)
