### ISSUE TITLE
how are disconnects handled?

### ISSUE THREAD

**Issue by flippyhead** [aaronblohowiak/Push-It#3]
When an agent disconnects (by closing their browser say) is that propagated up somehow?

**Comment by aaronblohowiak** [comment]
Not in a good way, currently.

Through the underlying socket.io can throw a disconnect, which will include the Client (socket.io's concept of the user) but not the Agent (Push-It's concept of the user.)

I am very interested in what your use-case is for this, and how you would expect it to work -- this is something I would like to support but I have not yet decided on the best way to expose it.  The code is written 

https://github.com/aaronblohowiak/Push-It/blob/master/server/etc/push-it-proto.js#L167

But the function body is currently 'null' ;)

=)

**Comment by aaronblohowiak** [comment]
Do you have any feedback about how you'd expect this to work?

**Comment by flippyhead** [comment]
I guess I don't really. I was, perhaps incorrectly, concerned that a bunch of stale connections would stick around but that seems not to be the case. For now it seems to work fine.

**Comment by aaronblohowiak** [comment]
Ah okay, cool.  If this becomes an issue, let me know.

**Comment by aaronblohowiak** [comment]
BTW, I implemented onDisconnect today.  https://github.com/aaronblohowiak/Push-It/commit/6af920734ca7ad32fd46459abca7ac0368654dc8

This passes in the agent to your onDisconnect handler.
