### ISSUE TITLE
difference between "data" and "message" properties 

### ISSUE THREAD

**Issue by flippyhead** [aaronblohowiak/Push-It#4]
I'm a little confused about the difference between the "data" property and "message". On the one hand channel and message are required, but in other cases there is data which contains what was set on the message. Thanks!

**Comment by aaronblohowiak** [comment]
whoops, i had replied on the other issue =)  I am going to fix this tonight. thanks.

**Comment by aaronblohowiak** [comment]
Thanks!  I updated the client.js to reflect this change, and have updated the deubg/ example so it should work out of the box again

  :-)

I've also added a CHANGELOG file which will document the changes that I'm making.
