### ISSUE TITLE
Push-It client and jQuery 1.5 compatibility

### ISSUE THREAD

**Issue by dwightgunning** [aaronblohowiak/Push-It#7]
After updating to jQuery 1.5 there seems to be a scoping/referencing problem with the socket.io member of the Push-It client.

I'm getting a "this.socket" not initialized error (client/push-it.js:113 in master).

Verified that reverting to jQuery 1.4.4 resolved the issue. It's probably a simple fix but don't have time right now... I'll look into it more after work.

Thanks,

Dwight

**Comment by aaronblohowiak** [comment]
I'll look into it after work tomorow (it's 11:48pm here...)

**Comment by dwightgunning** [comment]
For some reason jQuery .ready() callback isn't firing. Line 18... implemented with the $(function notation.

I've tried changing the client to use the more explicit notations described in the jQuery docs... http://api.jquery.com/ready/ and http://api.jquery.com/jQuery/#jQuery3 ... but no dice.

Next I will create a cleaner/basic test page outside of the app I'm developing to rule out any namespace clashes etc. Let me come back to you.

Regards,

Dwight

**Comment by aaronblohowiak** [comment]
You sir, are a scholar and a gentleman.  Thanks for looking into this.

**Comment by maritz** [comment]
Sooo... does it work with 1.5.x now? :D

**Comment by dwightgunning** [comment]
I've been majorly sidetracked so haven't had a chance to fix this up and
submit a pull request.

You'll hear when I do.

## Dwight

Dwight Gunning
Amsterdam, The Netherlands.
+31 (0)6 2363 8344 | Twitter/Skype: dwightgunning
dwight@dwightgunning.com | http://dwightgunning.com

**Comment by aaronblohowiak** [comment]
@dwightgunning, if you want I can take care of this tomorrow =)

**Comment by dwightgunning** [comment]
Yezzz please :-)
On Mar 18, 2011 12:27 AM, "aaronblohowiak" <
reply@reply.github.com>
wrote:

**Comment by aaronblohowiak** [comment]
Everything seems to be working for me in 1.5.2 in Firefox and Chrome.  The "debug" example is working fine.. are you still having an issue?

**Comment by dwightgunning** [comment]
I _still_ haven't had a chance to dive back into the development (boo!!!!)
but I trust you on the fix!

Cheers,

Dwight
