### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by sentientmatter** [aaronblohowiak/Push-It#9]
I noticed a few documentation errors in the docs for Push-It:

1) In the client section, this line:

var msgId = pushIt.publish(channel, data, onError, onSuccess);

should be:

var msgId = pushIt.publish(message, onError, onSuccess);

2) The couple lines referencing pushIt.TIMEOUTS says that the timeouts are in seconds, but the code is using standard milliseconds (also, 100ms seems a little low to me for the pub/sub defaults).

3) In the section labeled 'created / destroyed at runtime', the 'message' part labels it's data as 'payload', which is misleading as data is always underneath the 'data' attribute.

**Comment by aaronblohowiak** [comment]
Changed to 1 second instead of 100ms.  The timeouts were for the server-side functions to respond to the message, but i could still see a case where you might want to have the default be more lenient, so I increased to 1000 milliseconds.  Also, updated the docs. thanks.

**Comment by sentientmatter** [comment]
Great! I think 1000ms is the sweet spot and that's what I had set my defaults to. I can foresee complex pub/sub operations taking over 100ms, especially if extra work is being done (credential checking that might require a network round trip, for example)
